"""create lsa profiles table

Revision ID: 13dd4135255b
Revises: 110d1551a883
Create Date: 2026-08-12 14:21:02.565706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dd4135255b'
down_revision = '110d1551a883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lsa_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lsa_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lsa_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_lsa_profiles_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lsa_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lsa_profiles_is_active'))
        batch_op.drop_index(batch_op.f('ix_lsa_profiles_email'))

    op.drop_table('lsa_profiles')
    # ### end Alembic commands ###
