"""create booking requests table

Revision ID: 680d679d84e4
Revises: 13dd4135255b
Create Date: 2026-08-12 14:24:57.249609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680d679d84e4'
down_revision = '13dd4135255b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('lsa_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'FAILED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lsa_id'], ['lsa_profiles.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_requests_lsa_id'), ['lsa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_requests_status'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_start_time'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_parent_id'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_lsa_id'))

    op.drop_table('booking_requests')
    # ### end Alembic commands ###
